import { getRuntimeSchemaTables } from './runtime-tables.js';

export * from './shared/enums';
export type * from './sqlite';

// Runtime code imports table objects from this barrel throughout the app. Keep
// those imports dialect-aware so DB_MODE=postgres does not accidentally build
// queries with SQLite table definitions.
const runtimeSchema = getRuntimeSchemaTables();

export const {
  MARKETPLACE_STATUSES,
  PLUGIN_TAGS,
  SYNC_INTERVAL_OPTIONS,
  TEMPLATE_SCOPES,
  TEMPLATE_STATUSES,
  TERRAFORM_REGISTRY_STATUSES,
  WORKFLOW_STATUSES,
  agentRuns,
  agentRunsRelations,
  agents,
  agentsRelations,
  apiKeys,
  apiTokens,
  apiTokensRelations,
  auditLogs,
  cliSessions,
  codespaceMembers,
  codespaceMembersRelations,
  codespaceTags,
  codespaceTagsRelations,
  codespaces,
  codespacesRelations,
  dreamSessions,
  dreamSessionsRelations,
  eventLog,
  eventLogRelations,
  eventOutbox,
  eventSources,
  eventSourcesRelations,
  eventSubscriptions,
  eventSubscriptionsRelations,
  folderMembers,
  folderMembersRelations,
  githubInstallations,
  githubInstallationsRelations,
  githubTokens,
  marketplaces,
  memoryInsights,
  memoryInsightsRelations,
  memoryMessages,
  memoryMessagesRelations,
  planSessions,
  planSessionsRelations,
  projectFolders,
  projectFoldersRelations,
  rateLimitBuckets,
  repositoryConfigs,
  repositoryConfigsRelations,
  sandboxConfigs,
  sandboxConfigsRelations,
  sandboxInstances,
  sandboxInstancesRelations,
  sandboxTmuxSessions,
  sandboxTmuxSessionsRelations,
  scheduleExecutions,
  sessionEvents,
  sessionEventsRelations,
  sessionSummaries,
  sessionSummariesRelations,
  sessions,
  sessionsRelations,
  settings,
  skillExecutions,
  skillExecutionsRelations,
  skillMetrics,
  skillMetricsRelations,
  skillSuggestions,
  skillSuggestionsRelations,
  tags,
  tagsRelations,
  taskTags,
  taskTagsRelations,
  tasks,
  tasksRelations,
  teamInvitations,
  teamInvitationsRelations,
  teamMembers,
  teamMembersRelations,
  teamProjectFolders,
  teamProjectFoldersRelations,
  teams,
  teamsRelations,
  templateCodespaces,
  templateCodespacesRelations,
  templates,
  templatesRelations,
  terraformModules,
  terraformModulesRelations,
  terraformRegistries,
  terraformRegistriesRelations,
  userSessions,
  userSessionsRelations,
  users,
  usersRelations,
  workflows,
  worktrees,
  worktreesRelations,
} = runtimeSchema;
