{{- if and (include "agentpane.openshift.enabled" .) .Values.webhookRoute.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "agentpane.fullname" . }}-webhooks
  labels:
    {{- include "agentpane.labels" . | nindent 4 }}
spec:
  host: {{ .Values.webhookRoute.hostname }}
  path: /hooks/events
  to:
    kind: Service
    name: {{ include "agentpane.fullname" . }}
  port:
    targetPort: 3001
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
{{- end }}
